Routes/formroutes
prakash2003pramanick/FED-Backend pull request #5
Opened 2024-06-22 20:29 UTC by AnshRaj112

updating readme next

2024-06-22 20:49 UTC, prakash2003pramanick requested changes

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> +router.delete('/deleteForm/:id', deleteForm);
Add validations !!

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> +router.put('/editForm/:id', editForm);
Add validations !!

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.post('/addForm', formController.addForm )
Add validations !!
router.post('/addForm', formController.addForm )

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.delete('/deleteForm/:id', formController.deleteForm)
Why deleted the line ?
router.delete('/deleteForm/:id', formController.deleteForm)
Add validations !!

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.put('/editForm/:id', formController.editForm)
router.put('/editForm/:id', formController.editForm)

Add validations ... why this line is deleted?

2024-06-22 20:49 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -const {verifyToken} = require('../../middleware/verifyToken');
const formController = require('../../controllers/forms/formController')
const registrationController = require('../../controllers/registration/registrationController');
const {verifyToken} = require('../../middleware/verifyToken');

why eleted ?

2024-06-23 04:04 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -const {verifyToken} = require('../../middleware/verifyToken');
verify token is being called already in different line

2024-06-23 04:08 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -const {verifyToken} = require('../../middleware/verifyToken');
Why registraionController?

2024-06-23 04:10 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -const {verifyToken} = require('../../middleware/verifyToken');
form controller is being called by 
const { addForm, editForm, deleteForm, getAllForms } = require('../../controllers/forms/formController');

2024-06-23 04:11 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -router.put('/editForm/:id', formController.editForm)
formController is called in different way, no need for those lines

2024-06-23 04:12 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -router.delete('/deleteForm/:id', formController.deleteForm)
deletefom is called by 
const { addForm, editForm, deleteForm, getAllForms } = require('../../controllers/forms/formController');
by this line all addform, editform, deleteform and getallforms are being called from formcontroller

2024-06-23 04:13 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -router.post('/addForm', formController.addForm )
addform is called by
const { addForm, editForm, deleteForm, getAllForms } = require('../../controllers/forms/formController');
by this line all addform, editform, deleteform and getallforms are being called from formcontroller

2024-06-23 04:29 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> +router.put('/editForm/:id', editForm);
router.delete('/deleteForm/:id', validate, deleteForm);
this correct?

2024-06-23 04:30 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> +router.delete('/deleteForm/:id', deleteForm);
router.delete('/deleteForm/:id', validate, deleteForm);
this correct?

2024-06-23 04:31 UTC, AnshRaj112 commented on routes/forms/formRoutes.js
> -router.post('/addForm', formController.addForm )
router.post('/addForm', addFormValidationRules(), validate, addForm);
correct?

2024-06-23 04:37 UTC, AnshRaj112 reviewed
calling addForm, editForm, deleteForm, getAllForms functions from formController.js, added validation, check and tell if correct or needs changes

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -const {verifyToken} = require('../../middleware/verifyToken');
form registration controller is required in form routes only 
dont destruct formcontroller in case we have more then the list will be very large its better to use using formController.addForm like this

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.get('/getAllForms',formController.getAllForms)
router.get('/getAllForms',formController.getAllForms)
keep this line

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.get('/download/:id', verifyToken, registrationController.downloadRegistration)
router.use('/register', verifyToken, registrationController.addRegistration)
router.get('/download/:id', verifyToken, registrationController.downloadRegistration)

include

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.delete('/deleteForm/:id', formController.deleteForm)
this is not an import line

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.post('/addForm', formController.addForm )
is like this

2024-06-23 08:39 UTC, prakash2003pramanick commented on routes/forms/formRoutes.js
> -router.put('/editForm/:id', formController.editForm)
use this syntax
router.put('/editForm/:id', formController.editForm)

2024-06-25 16:36 UTC, closed without merging